/**
 *
 *  TSchedulePos.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TSchedulePos.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::workflow;

const std::string TSchedulePos::Cols::_id = "id";
const std::string TSchedulePos::Cols::_task_type = "task_type";
const std::string TSchedulePos::Cols::_data_begin_pos = "data_begin_pos";
const std::string TSchedulePos::Cols::_data_end_pos = "data_end_pos";
const std::string TSchedulePos::Cols::_schedule_begin_pos = "schedule_begin_pos";
const std::string TSchedulePos::Cols::_schedule_end_pos = "schedule_end_pos";
const std::string TSchedulePos::Cols::_create_time = "create_time";
const std::string TSchedulePos::Cols::_modify_time = "modify_time";
const std::string TSchedulePos::primaryKeyName = "id";
const bool TSchedulePos::hasPrimaryKey = true;
const std::string TSchedulePos::tableName = "t_schedule_pos";

const std::vector<typename TSchedulePos::MetaData> TSchedulePos::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"task_type","std::string","varchar(256)",256,0,0,1},
{"data_begin_pos","int32_t","int",4,0,0,1},
{"data_end_pos","int32_t","int",4,0,0,1},
{"schedule_begin_pos","int32_t","int",4,0,0,1},
{"schedule_end_pos","int32_t","int",4,0,0,1},
{"create_time","::trantor::Date","datetime",0,0,0,1},
{"modify_time","::trantor::Date","datetime",0,0,0,1}
};
const std::string &TSchedulePos::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TSchedulePos::TSchedulePos(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["task_type"].isNull())
        {
            taskType_=std::make_shared<std::string>(r["task_type"].as<std::string>());
        }
        if(!r["data_begin_pos"].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>(r["data_begin_pos"].as<int32_t>());
        }
        if(!r["data_end_pos"].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>(r["data_end_pos"].as<int32_t>());
        }
        if(!r["schedule_begin_pos"].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>(r["schedule_begin_pos"].as<int32_t>());
        }
        if(!r["schedule_end_pos"].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>(r["schedule_end_pos"].as<int32_t>());
        }
        if(!r["create_time"].isNull())
        {
            auto timeStr = r["create_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["modify_time"].isNull())
        {
            auto timeStr = r["modify_time"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            taskType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

TSchedulePos::TSchedulePos(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

TSchedulePos::TSchedulePos(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("task_type"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["task_type"].isNull())
        {
            taskType_=std::make_shared<std::string>(pJson["task_type"].asString());
        }
    }
    if(pJson.isMember("data_begin_pos"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["data_begin_pos"].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>((int32_t)pJson["data_begin_pos"].asInt64());
        }
    }
    if(pJson.isMember("data_end_pos"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["data_end_pos"].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>((int32_t)pJson["data_end_pos"].asInt64());
        }
    }
    if(pJson.isMember("schedule_begin_pos"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["schedule_begin_pos"].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>((int32_t)pJson["schedule_begin_pos"].asInt64());
        }
    }
    if(pJson.isMember("schedule_end_pos"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["schedule_end_pos"].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>((int32_t)pJson["schedule_end_pos"].asInt64());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["create_time"].isNull())
        {
            auto timeStr = pJson["create_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modify_time"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["modify_time"].isNull())
        {
            auto timeStr = pJson["modify_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TSchedulePos::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskType_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TSchedulePos::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("task_type"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["task_type"].isNull())
        {
            taskType_=std::make_shared<std::string>(pJson["task_type"].asString());
        }
    }
    if(pJson.isMember("data_begin_pos"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["data_begin_pos"].isNull())
        {
            dataBeginPos_=std::make_shared<int32_t>((int32_t)pJson["data_begin_pos"].asInt64());
        }
    }
    if(pJson.isMember("data_end_pos"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["data_end_pos"].isNull())
        {
            dataEndPos_=std::make_shared<int32_t>((int32_t)pJson["data_end_pos"].asInt64());
        }
    }
    if(pJson.isMember("schedule_begin_pos"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["schedule_begin_pos"].isNull())
        {
            scheduleBeginPos_=std::make_shared<int32_t>((int32_t)pJson["schedule_begin_pos"].asInt64());
        }
    }
    if(pJson.isMember("schedule_end_pos"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["schedule_end_pos"].isNull())
        {
            scheduleEndPos_=std::make_shared<int32_t>((int32_t)pJson["schedule_end_pos"].asInt64());
        }
    }
    if(pJson.isMember("create_time"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["create_time"].isNull())
        {
            auto timeStr = pJson["create_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("modify_time"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["modify_time"].isNull())
        {
            auto timeStr = pJson["modify_time"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                modifyTime_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int64_t &TSchedulePos::getValueOfId() const noexcept
{
    const static int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &TSchedulePos::getId() const noexcept
{
    return id_;
}
void TSchedulePos::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename TSchedulePos::PrimaryKeyType & TSchedulePos::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &TSchedulePos::getValueOfTaskType() const noexcept
{
    const static std::string defaultValue = std::string();
    if(taskType_)
        return *taskType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TSchedulePos::getTaskType() const noexcept
{
    return taskType_;
}
void TSchedulePos::setTaskType(const std::string &pTaskType) noexcept
{
    taskType_ = std::make_shared<std::string>(pTaskType);
    dirtyFlag_[1] = true;
}
void TSchedulePos::setTaskType(std::string &&pTaskType) noexcept
{
    taskType_ = std::make_shared<std::string>(std::move(pTaskType));
    dirtyFlag_[1] = true;
}

const int32_t &TSchedulePos::getValueOfDataBeginPos() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(dataBeginPos_)
        return *dataBeginPos_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TSchedulePos::getDataBeginPos() const noexcept
{
    return dataBeginPos_;
}
void TSchedulePos::setDataBeginPos(const int32_t &pDataBeginPos) noexcept
{
    dataBeginPos_ = std::make_shared<int32_t>(pDataBeginPos);
    dirtyFlag_[2] = true;
}

const int32_t &TSchedulePos::getValueOfDataEndPos() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(dataEndPos_)
        return *dataEndPos_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TSchedulePos::getDataEndPos() const noexcept
{
    return dataEndPos_;
}
void TSchedulePos::setDataEndPos(const int32_t &pDataEndPos) noexcept
{
    dataEndPos_ = std::make_shared<int32_t>(pDataEndPos);
    dirtyFlag_[3] = true;
}

const int32_t &TSchedulePos::getValueOfScheduleBeginPos() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(scheduleBeginPos_)
        return *scheduleBeginPos_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TSchedulePos::getScheduleBeginPos() const noexcept
{
    return scheduleBeginPos_;
}
void TSchedulePos::setScheduleBeginPos(const int32_t &pScheduleBeginPos) noexcept
{
    scheduleBeginPos_ = std::make_shared<int32_t>(pScheduleBeginPos);
    dirtyFlag_[4] = true;
}

const int32_t &TSchedulePos::getValueOfScheduleEndPos() const noexcept
{
    const static int32_t defaultValue = int32_t();
    if(scheduleEndPos_)
        return *scheduleEndPos_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &TSchedulePos::getScheduleEndPos() const noexcept
{
    return scheduleEndPos_;
}
void TSchedulePos::setScheduleEndPos(const int32_t &pScheduleEndPos) noexcept
{
    scheduleEndPos_ = std::make_shared<int32_t>(pScheduleEndPos);
    dirtyFlag_[5] = true;
}

const ::trantor::Date &TSchedulePos::getValueOfCreateTime() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(createTime_)
        return *createTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TSchedulePos::getCreateTime() const noexcept
{
    return createTime_;
}
void TSchedulePos::setCreateTime(const ::trantor::Date &pCreateTime) noexcept
{
    createTime_ = std::make_shared<::trantor::Date>(pCreateTime);
    dirtyFlag_[6] = true;
}

const ::trantor::Date &TSchedulePos::getValueOfModifyTime() const noexcept
{
    const static ::trantor::Date defaultValue = ::trantor::Date();
    if(modifyTime_)
        return *modifyTime_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TSchedulePos::getModifyTime() const noexcept
{
    return modifyTime_;
}
void TSchedulePos::setModifyTime(const ::trantor::Date &pModifyTime) noexcept
{
    modifyTime_ = std::make_shared<::trantor::Date>(pModifyTime);
    dirtyFlag_[7] = true;
}

void TSchedulePos::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &TSchedulePos::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "task_type",
        "data_begin_pos",
        "data_end_pos",
        "schedule_begin_pos",
        "schedule_end_pos",
        "create_time",
        "modify_time"
    };
    return inCols;
}

void TSchedulePos::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTaskType())
        {
            binder << getValueOfTaskType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDataBeginPos())
        {
            binder << getValueOfDataBeginPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDataEndPos())
        {
            binder << getValueOfDataEndPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getScheduleBeginPos())
        {
            binder << getValueOfScheduleBeginPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getScheduleEndPos())
        {
            binder << getValueOfScheduleEndPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getModifyTime())
        {
            binder << getValueOfModifyTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TSchedulePos::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void TSchedulePos::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTaskType())
        {
            binder << getValueOfTaskType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDataBeginPos())
        {
            binder << getValueOfDataBeginPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDataEndPos())
        {
            binder << getValueOfDataEndPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getScheduleBeginPos())
        {
            binder << getValueOfScheduleBeginPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getScheduleEndPos())
        {
            binder << getValueOfScheduleEndPos();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getCreateTime())
        {
            binder << getValueOfCreateTime();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getModifyTime())
        {
            binder << getValueOfModifyTime();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TSchedulePos::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTaskType())
    {
        ret["task_type"]=getValueOfTaskType();
    }
    else
    {
        ret["task_type"]=Json::Value();
    }
    if(getDataBeginPos())
    {
        ret["data_begin_pos"]=getValueOfDataBeginPos();
    }
    else
    {
        ret["data_begin_pos"]=Json::Value();
    }
    if(getDataEndPos())
    {
        ret["data_end_pos"]=getValueOfDataEndPos();
    }
    else
    {
        ret["data_end_pos"]=Json::Value();
    }
    if(getScheduleBeginPos())
    {
        ret["schedule_begin_pos"]=getValueOfScheduleBeginPos();
    }
    else
    {
        ret["schedule_begin_pos"]=Json::Value();
    }
    if(getScheduleEndPos())
    {
        ret["schedule_end_pos"]=getValueOfScheduleEndPos();
    }
    else
    {
        ret["schedule_end_pos"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getCreateTime()->toDbStringLocal();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    if(getModifyTime())
    {
        ret["modify_time"]=getModifyTime()->toDbStringLocal();
    }
    else
    {
        ret["modify_time"]=Json::Value();
    }
    return ret;
}

Json::Value TSchedulePos::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTaskType())
            {
                ret[pMasqueradingVector[1]]=getValueOfTaskType();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDataBeginPos())
            {
                ret[pMasqueradingVector[2]]=getValueOfDataBeginPos();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDataEndPos())
            {
                ret[pMasqueradingVector[3]]=getValueOfDataEndPos();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getScheduleBeginPos())
            {
                ret[pMasqueradingVector[4]]=getValueOfScheduleBeginPos();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getScheduleEndPos())
            {
                ret[pMasqueradingVector[5]]=getValueOfScheduleEndPos();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getCreateTime())
            {
                ret[pMasqueradingVector[6]]=getCreateTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getModifyTime())
            {
                ret[pMasqueradingVector[7]]=getModifyTime()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTaskType())
    {
        ret["task_type"]=getValueOfTaskType();
    }
    else
    {
        ret["task_type"]=Json::Value();
    }
    if(getDataBeginPos())
    {
        ret["data_begin_pos"]=getValueOfDataBeginPos();
    }
    else
    {
        ret["data_begin_pos"]=Json::Value();
    }
    if(getDataEndPos())
    {
        ret["data_end_pos"]=getValueOfDataEndPos();
    }
    else
    {
        ret["data_end_pos"]=Json::Value();
    }
    if(getScheduleBeginPos())
    {
        ret["schedule_begin_pos"]=getValueOfScheduleBeginPos();
    }
    else
    {
        ret["schedule_begin_pos"]=Json::Value();
    }
    if(getScheduleEndPos())
    {
        ret["schedule_end_pos"]=getValueOfScheduleEndPos();
    }
    else
    {
        ret["schedule_end_pos"]=Json::Value();
    }
    if(getCreateTime())
    {
        ret["create_time"]=getCreateTime()->toDbStringLocal();
    }
    else
    {
        ret["create_time"]=Json::Value();
    }
    if(getModifyTime())
    {
        ret["modify_time"]=getModifyTime()->toDbStringLocal();
    }
    else
    {
        ret["modify_time"]=Json::Value();
    }
    return ret;
}

bool TSchedulePos::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("task_type"))
    {
        if(!validJsonOfField(1, "task_type", pJson["task_type"], err, true))
            return false;
    }
    else
    {
        err="The task_type column cannot be null";
        return false;
    }
    if(pJson.isMember("data_begin_pos"))
    {
        if(!validJsonOfField(2, "data_begin_pos", pJson["data_begin_pos"], err, true))
            return false;
    }
    if(pJson.isMember("data_end_pos"))
    {
        if(!validJsonOfField(3, "data_end_pos", pJson["data_end_pos"], err, true))
            return false;
    }
    if(pJson.isMember("schedule_begin_pos"))
    {
        if(!validJsonOfField(4, "schedule_begin_pos", pJson["schedule_begin_pos"], err, true))
            return false;
    }
    if(pJson.isMember("schedule_end_pos"))
    {
        if(!validJsonOfField(5, "schedule_end_pos", pJson["schedule_end_pos"], err, true))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(6, "create_time", pJson["create_time"], err, true))
            return false;
    }
    if(pJson.isMember("modify_time"))
    {
        if(!validJsonOfField(7, "modify_time", pJson["modify_time"], err, true))
            return false;
    }
    return true;
}
bool TSchedulePos::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TSchedulePos::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("task_type"))
    {
        if(!validJsonOfField(1, "task_type", pJson["task_type"], err, false))
            return false;
    }
    if(pJson.isMember("data_begin_pos"))
    {
        if(!validJsonOfField(2, "data_begin_pos", pJson["data_begin_pos"], err, false))
            return false;
    }
    if(pJson.isMember("data_end_pos"))
    {
        if(!validJsonOfField(3, "data_end_pos", pJson["data_end_pos"], err, false))
            return false;
    }
    if(pJson.isMember("schedule_begin_pos"))
    {
        if(!validJsonOfField(4, "schedule_begin_pos", pJson["schedule_begin_pos"], err, false))
            return false;
    }
    if(pJson.isMember("schedule_end_pos"))
    {
        if(!validJsonOfField(5, "schedule_end_pos", pJson["schedule_end_pos"], err, false))
            return false;
    }
    if(pJson.isMember("create_time"))
    {
        if(!validJsonOfField(6, "create_time", pJson["create_time"], err, false))
            return false;
    }
    if(pJson.isMember("modify_time"))
    {
        if(!validJsonOfField(7, "modify_time", pJson["modify_time"], err, false))
            return false;
    }
    return true;
}
bool TSchedulePos::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TSchedulePos::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            // asString().length() creates a string object, is there any better way to validate the length?
            if(pJson.isString() && pJson.asString().length() > 256)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 256)";
                return false;
            }

            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
