/**
 *
 *  TScheduleCfg.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace workflow
{

class TScheduleCfg
{
  public:
    struct Cols
    {
        static const std::string _task_type;
        static const std::string _schedule_limit;
        static const std::string _schedule_interval;
        static const std::string _max_processing_time;
        static const std::string _max_retry_num;
        static const std::string _retry_interval;
        static const std::string _create_time;
        static const std::string _modify_time;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit TScheduleCfg(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit TScheduleCfg(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    TScheduleCfg(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    TScheduleCfg() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column task_type  */
    ///Get the value of the column task_type, returns the default value if the column is null
    const std::string &getValueOfTaskType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTaskType() const noexcept;
    ///Set the value of the column task_type
    void setTaskType(const std::string &pTaskType) noexcept;
    void setTaskType(std::string &&pTaskType) noexcept;

    /**  For column schedule_limit  */
    ///Get the value of the column schedule_limit, returns the default value if the column is null
    const int32_t &getValueOfScheduleLimit() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getScheduleLimit() const noexcept;
    ///Set the value of the column schedule_limit
    void setScheduleLimit(const int32_t &pScheduleLimit) noexcept;
    void setScheduleLimitToNull() noexcept;

    /**  For column schedule_interval  */
    ///Get the value of the column schedule_interval, returns the default value if the column is null
    const int32_t &getValueOfScheduleInterval() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getScheduleInterval() const noexcept;
    ///Set the value of the column schedule_interval
    void setScheduleInterval(const int32_t &pScheduleInterval) noexcept;

    /**  For column max_processing_time  */
    ///Get the value of the column max_processing_time, returns the default value if the column is null
    const int32_t &getValueOfMaxProcessingTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxProcessingTime() const noexcept;
    ///Set the value of the column max_processing_time
    void setMaxProcessingTime(const int32_t &pMaxProcessingTime) noexcept;
    void setMaxProcessingTimeToNull() noexcept;

    /**  For column max_retry_num  */
    ///Get the value of the column max_retry_num, returns the default value if the column is null
    const int32_t &getValueOfMaxRetryNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getMaxRetryNum() const noexcept;
    ///Set the value of the column max_retry_num
    void setMaxRetryNum(const int32_t &pMaxRetryNum) noexcept;
    void setMaxRetryNumToNull() noexcept;

    /**  For column retry_interval  */
    ///Get the value of the column retry_interval, returns the default value if the column is null
    const int32_t &getValueOfRetryInterval() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getRetryInterval() const noexcept;
    ///Set the value of the column retry_interval
    void setRetryInterval(const int32_t &pRetryInterval) noexcept;
    void setRetryIntervalToNull() noexcept;

    /**  For column create_time  */
    ///Get the value of the column create_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfCreateTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getCreateTime() const noexcept;
    ///Set the value of the column create_time
    void setCreateTime(const ::trantor::Date &pCreateTime) noexcept;
    void setCreateTimeToNull() noexcept;

    /**  For column modify_time  */
    ///Get the value of the column modify_time, returns the default value if the column is null
    const ::trantor::Date &getValueOfModifyTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getModifyTime() const noexcept;
    ///Set the value of the column modify_time
    void setModifyTime(const ::trantor::Date &pModifyTime) noexcept;
    void setModifyTimeToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 8;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<TScheduleCfg>;
    friend drogon::orm::BaseBuilder<TScheduleCfg, true, true>;
    friend drogon::orm::BaseBuilder<TScheduleCfg, true, false>;
    friend drogon::orm::BaseBuilder<TScheduleCfg, false, true>;
    friend drogon::orm::BaseBuilder<TScheduleCfg, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<TScheduleCfg>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> taskType_;
    std::shared_ptr<int32_t> scheduleLimit_;
    std::shared_ptr<int32_t> scheduleInterval_;
    std::shared_ptr<int32_t> maxProcessingTime_;
    std::shared_ptr<int32_t> maxRetryNum_;
    std::shared_ptr<int32_t> retryInterval_;
    std::shared_ptr<::trantor::Date> createTime_;
    std::shared_ptr<::trantor::Date> modifyTime_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[8]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where task_type = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where task_type = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "task_type,";
            ++parametersCount;
        }
        sql += "schedule_limit,";
        ++parametersCount;
        if(!dirtyFlag_[1])
        {
            needSelection=true;
        }
        sql += "schedule_interval,";
        ++parametersCount;
        if(!dirtyFlag_[2])
        {
            needSelection=true;
        }
        sql += "max_processing_time,";
        ++parametersCount;
        if(!dirtyFlag_[3])
        {
            needSelection=true;
        }
        sql += "max_retry_num,";
        ++parametersCount;
        if(!dirtyFlag_[4])
        {
            needSelection=true;
        }
        if(dirtyFlag_[5])
        {
            sql += "retry_interval,";
            ++parametersCount;
        }
        sql += "create_time,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "modify_time,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[0])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        else
        {
            sql +="default,";
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace workflow
} // namespace drogon_model
